### PR TITLE
add reload endpoint

### PR DESCRIPTION
**Pull request by killix**
Set the ability to reload the cache from S3.

### CODE REVIEW

**Comment by alexcarruthers** [comment]
hi phred! this is useful for when we add images

**Comment by kiasaki** [comment]
Nice, thanks for this @killix.

I'd like to merge this but have you tried simply calling `.Setup()` on the current cache object?

It seems like this would help you avoid the downtime of having an empty cache for 15-30 seconds and simply overwrite existing cached files.

Looking at `.Setup()`: https://github.com/kiasaki/coresize/blob/master/cache.go#L100

Tell me what you think.

**Comment by kiasaki** [comment]
Just to be clear what I meant is I don't think this line https://github.com/kiasaki/coresize/pull/3/files#diff-31a4a7824225629df071a1cba8b785d5R61 helps ;)

**Comment by alexcarruthers** [comment]
@kiasaki the only thing i can think of there is it wouldn't handle deleted items well (not that we actually delete things often....)

**Comment by killix** [comment]
:+1: @alexcarruthers this suggestion only update the new files.

**Comment by killix** [comment]
@kiasaki: what do you think ?

**Comment by kiasaki** [comment]
Simple then, create a new cache in the local scope, call `.Setup()`, wait for it to complete, replace the old `Cache` prop on the server struct.

Something like:

```go
cache := NewCache(s.Config)
if err := cache.Setup(); err != nil {
	log.Printf("Error setting up cache: %s\n", err.Error())
	rest.SetInternalServerErrorResponse(w, err)
        return
}
s.Cache = cache
```

**Comment by killix** [comment]
:+1:

**Comment by kiasaki** [comment]
:shipit:

**Pull request merged**
